version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      # MYSQL_DATABASE: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/happydiary
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  mysql-data:
  bundle:
